import catImage from "./img/c.cat.png";
import dogImage from "./img/c.dog.png";
import rabbitImage from "./img/c.rabbit.png";
import parrotImage from "./img/c.parrot.png";
import hamsterImage from "./img/c.hamster.png";
import paw from "./img/paw.png";

export const dogData = {
  name: "Câine",
  rasa: [
    "Afghan Hound",
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "American Bulldog",
    "American Bulldog",
    "American Eskimo",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Barzoi",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Laekenois",
    "Belgian Malinois",
    "Belgian Sheepdog",
    "Belgian Tervuren",
    "Bernese Mountain Dog",
    "Bichon Bolognese",
    "Bichon Frise",
    "Bichon Havanais",
    "Bloodhound",
    "Bolognese",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Briard",
    "Bulldog Francez",
    "Bullmastiff",
    "Cairn Terrier",
    "Cavalier King Charles Spaniel",
    "Cesky Fousek",
    "Chesapeake Bay Retriever",
    "Chinese Crested Dog",
    "Chihuahua",
    "Chinook",
    "Chippiparai",
    "Chow-Chow",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Collie",
    "Continental Toy Spaniel",
    "Coton de Tulear",
    "Czechoslovakian Wolfdog",
    "Dachshund",
    "Dalmatian",
    "Danish-Swedish Farmdog",
    "Deerhound",
    "Doberman",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "Dogo Canario",
    "English Bulldog",
    "English Setter",
    "Entlebuch Shepherd Dog",
    "Eurasian",
    "Euro Mountain Sheparnese",
    "Field Spaniel",
    "Fila Brasileiro",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "French Bulldog",
    "French Spaniel",
    "German Longhaired Pointer",
    "German Pinscher",
    "German Shepherd",
    "German Shorthaired Pointer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Gordon Setter",
    "Griffon de Bruxelles",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Havanese",
    "Heideterrier",
    "Hovawart",
    "Huskita",
    "Husky Arctic",
    "Husky Siberian",
    "Ibizan Hound",
    "Irish Setter",
    "Irish Terrier",
    "Irish Woulfhound",
    "Italian Greyhound",
    "Italian Tzu",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Japanese Spitz",
    "Karelian Bear Dog",
    "Keeshond",
    "Kerry Blue Terrier",
    "Kintamani",
    "Komondor",
    "Kooikerhondje",
    "Koreean Jindo Dog",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Laika",
    "Lancashire Heeler",
    "Landseer",
    "Laika",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Laika",
    "Leonberger",
    "Lhasa Apso",
    "Limier Bavarez",
    "Limier De Hanovra",
    "Longhaired Dachshund",
    "Lundehund",
    "Löwchen",
    "Mahratta Greyhound",
    "Malinois Ciobenesc Belgian",
    "Maltese",
    "Maremma Sheepdog",
    "Mastiff",
    "Mastino Napoletano",
    "Matis",
    "McNab",
    "Mexican Hairless Dog",
    "Miniature Dachshund",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Moodle",
    "Moscow Watchdog",
    "Mudi",
    "Mudhol Hound",
    "Neapolitan Mastiff",
    "New Guinea Singing Dog",
    "Newfoundland",
    "Norfolk Terrier",
    "Norrbottenspets",
    "Northern Inuit Dog",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Pakistani Mastiff",
    "Pandikona",
    "Papillon",
    "Parson Russell Terrier",
    "Patterdale Terrier",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Perro de Presa Canario",
    "Peruvian Inca Orchid",
    "Petit Basset Griffon Vendéen",
    "Pharaoh Hound",
    "Plott Hound",
    "Pointer",
    "Polish Lowland Sheepdog",
    "Pomeranian",
    "Poodle",
    "Poodle Toy",
    "Presa Canario",
    "Pug",
    "Pugalier",
    "Puli",
    "Pumi",
    "Pyrenean Mastiff",
    "Pyrenean Shepherd",
    "Rafeiro do Alentejo",
    "Rajapalayam",
    "Rampur Greyhound",
    "Rat Terrier",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Romanian Mioritic Shepherd Dog",
    "Rottweiler",
    "Russian Spaniel",
    "Russian Toy Terrier",
    "Russkiy Toy",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schapendoes",
    "Schillerstövare",
    "Schipperke",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Segugio Italiano",
    "Serbian Hound",
    "Shetland Sheepdog",
    "Shih Tzu",
    "Shikoku",
    "Siberian Husky",
    "Silken Windhound",
    "Slovak Cuvac",
    "Slovakian Rough-haired Pointer",
    "Small Munsterlander",
    "Smooth Fox Terrier",
    "Soft-Coated Wheaten Terrier",
    "Spanish Mastiff",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Swedish Lapphund",
    "Swedish Vallhund",
    "Tahltan Bear Dog",
    "Tenterfield Terrier",
    "Tervuren",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Tosa",
    "Toy Fox Terrier",
    "Toy Manchester Terrier",
    "Toy Poodle",
    "Transylvanian Hound",
    "Treeing Tennessee Brindle",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "West Siberian Laika",
    "Whippet",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Wirehaired Vizsla",
    "Xoloitzcuintli",
    "Yorkshire Terrier",
  ],
  image: dogImage,
};

export const catData = {
  name: "Pisică",
  rasa: [
    "Abyssinian",
    "American Curl",
    "American Shorthair",
    "American Shorthair",
    "American Shorthair",
    "American Wirehair",
    "Australian Mist",
    "Arabian Mau",
    "African Wild",
    "Balinese",
    "Bengal",
    "Birmaneza",
    "Bombay",
    "British Shorthair",
    "Brazilian Shorthair",
    "Burmilla",
    "British Longhair",
    "Black Footed",
    "Chartreux",
    "Cornish Rex",
    "Cymric",
    "Chausie",
    "Chantilly Tiffany",
    "Chinchilla",
    "Calico",
    "Caracal",
    "Devon Rex",
    "Dward",
    "Exotic Shorthair",
    "Egyptian Mau",
    "Havana Brown",
    "Himalayan",
    "Javanese",
    "Japanese Bobtail",
    "Korat",
    "Khao Manee",
    "LaPerm",
    "Maine Coon",
    "Munchkin",
    "Norwegian Forest",
    "Nebelug",
    "Ocicat",
    "Oriental",
    "Persană",
    "Peterbald",
    "Pixie Bob",
    "Russian Blue",
    "Ragamuffin",
    "Ragdoll",
    "Scottish Fold",
    "Scottish Straight",
    "Scottish Shorthair",
    "Siberiană",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Siameză",
    "Sphynx",
    "Savannah",
    "Serval",
    "Skookum",
    "Tonkinese",
    "Turkish Angora",
    "Turkish Van",
    "Tabby",
    "Unknown",
  ],
  image: catImage,
};

export const rabbitData = {
  name: "Iepure",
  rasa: [
    "Altex",
    "American Blue",
    "Angora",
    "Alaska",
    "American Fuzzy Lop",
    "American Sable",
    "Argente",
    "Argente Brun",
    "Argente Creme",
    "Argente de Champagne",
    "Beveren",
    "Belgian Hare",
    "Britannia Petite",
    "California",
    "Checkered Giant",
    "Continental Giant",
    "Chinchilla Standard",
    "Chinchilla American",
    "Chinchilla Giant",
    "Cinammon",
    "Dutch",
    "Dwarf Lop",
    "Dwarf Hotot",
    "English Angora",
    "English Lop",
    "English Spor",
    "Flemish",
    "French Lop",
    "Florida White",
    "French Angora",
    "Giant",
    "Giant Angora",
    "Giant Papillon",
    "German Lop",
    "Hare",
    "harlequin",
    "Hotot",
    "Holland Lop",
    "Havana",
    "Himalayan",
    "Jersey Wooly",
    "Lilan",
    "Lop",
    "Lionhead",
    "Mini Lop",
    "Miniature Lop",
    "Mini Rex",
    "Netherlamd Dwarf",
    "New Zealand",
    "Plush Lop",
    "Polish",
    "Palomino",
    "Rex",
    "Silver Fox",
    "Silver Marten",
    "Scrub Here",
    "Satin Angora",
    "Transilvania Giant",
    "Thrianta",
    "Tan",
    "Velveteen Lop",
  ],
  image: rabbitImage,
};

export const parrotData = {
  name: "Papagal",
  rasa: [
    "African Grey",
    "Amazonian Parrotlet",
    "Australian Ringneck",
    "Călugăr (Quaker)",
    "Collared Lory",
    "Ara",
    "Amazon",
    "Alexandrine",
    "Blue Fronted Amazon",
    "Collared Lory",
    "Cacadu (Cockatoo)",
    "Cockatiel",
    "Green-cheeked conure",
    "Lovebird",
    "Nimfă (Conure)",
    "Perus",
    "Rosella",
    "Rainbow Lorikeet",
    "Senegal",
    "White Bellied Caique",
  ],
  image: parrotImage,
};

export const hamsterData = {
  name: "Hamster",
  rasa: [
    "Sirian",
    "Pitic Rusesc (Campbell's)",
    "Djungarian (Winter White)",
    "Chinese",
    "Roborovski",
  ],
  image: hamsterImage,
};

export const OtherData = {
  name: "Alt animal",
  rasa: ["Altă rasă"],
  image: paw,
};

export const pets = [
  dogData,
  catData,
  rabbitData,
  parrotData,
  hamsterData,
  OtherData,
];
